import { createAppConfig } from '../app';

describe('createAppConfig', () => {
  const appURL = 'https://hypothes.is/app.html';

  /**
   * Filter configuration generated by `createAppConfig` to remove properties
   * which are always added regardless of the input.
   */
  function filterConfig(config) {
    return Object.fromEntries(
      Object.entries(config).filter(
        ([key]) => key !== 'hostURL' && key !== 'origin' && key !== 'version',
      ),
    );
  }

  it('copies config values', () => {
    const config = {
      showHighlights: true,
      appType: 'via',
    };

    const sidebarConfig = filterConfig(createAppConfig(appURL, config));

    assert.deepEqual(sidebarConfig, {
      showHighlights: true,
      appType: 'via',
    });
  });

  it('does not copy "notebookAppUrl" or "sidebarAppUrl" properties', () => {
    const config = {
      showHighlights: true,
      notebookAppUrl: 'https://hypothes.is/notebook.html',
      sidebarAppUrl: 'https://hypothes.is/app.html',
    };
    const sidebarConfig = filterConfig(createAppConfig(appURL, config));
    assert.deepEqual(sidebarConfig, {
      showHighlights: true,
    });
  });

  it('does not copy nullish values', () => {
    const config = {
      nullValue: null,
      undefinedValue: undefined,
      notNullValue: 'test',
    };

    const appConfig = filterConfig(createAppConfig(appURL, config));

    assert.deepEqual(appConfig, { notNullValue: 'test' });
  });

  it('adds client version to configuration', () => {
    const config = createAppConfig(appURL, {});
    assert.equal(config.version, '1.0.0-dummy-version');
  });

  it('adds host URL to configuration', () => {
    const config = createAppConfig(appURL, {});
    assert.equal(config.hostURL, window.location.href);
  });

  it('adds expected app origin to configuration', () => {
    const config = createAppConfig(appURL, {});
    assert.equal(config.origin, 'https://hypothes.is');
  });

  it('sets boolean properties to indicate presence of callbacks', () => {
    const callbacks = [
      'onLoginRequest',
      'onLogoutRequest',
      'onSignupRequest',
      'onProfileRequest',
      'onHelpRequest',
    ];
    const service = {};
    for (let callback of callbacks) {
      service[callback] = sinon.stub();
    }

    const config = {
      services: [service],
    };
    const sidebarConfig = createAppConfig(appURL, config);
    const sidebarServiceConfig = sidebarConfig.services[0];

    for (let callback of callbacks) {
      assert.equal(sidebarServiceConfig[callback + 'Provided'], true);
    }
  });
});
