name: 'Get Updated Package Version'
inputs:
  # The shared package name, "@hypothesis/frontend-shared"
  shared-package:
    required: true
    default: ''
    description: 'The npm package name'
  # The client package name, "hypothesis"
  parent-package:
    required: true
    default: ''
    description: 'The npm package name'
outputs:
  updated_version:
    description: 'The new version of the npm package'
runs:
  using: 'node12'
  main: 'index.js'