/**
 * Returns the extension ID which is running this script, or undefined if this
 * script is not being run by the browser extension.
 */
export function getExtensionId(window_: Window = window): string | undefined {
  return (window_ as any).chrome?.runtime?.id;
}

/**
 * Verifies if there's a config script in the document that was generated by a
 * specific browser extension.
 */
export function hasExtensionConfig(
  extensionId: string,
  document_: Document = document,
): boolean {
  return !!document_.querySelector(
    `script.js-hypothesis-config[data-extension-id=${extensionId}]`,
  );
}
