#!/bin/sh

set -eu

SEMVER=./node_modules/.bin/semver
CURRENT_VERSION=$(jq -r .version package.json)
NEW_VERSION=$($SEMVER -i minor "$CURRENT_VERSION")
yarn config set version-sign-git-tag true
yarn version --new-version $NEW_VERSION
